export const metadata = {
  title: 'Privacy Policy | CompressPro',
  alternates: {
    canonical: '/privacy-policy',
  },
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container mx-auto max-w-4xl p-8 py-16">
      <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

      <div className="space-y-6 text-gray-700 dark:text-gray-300">
        <p>Last updated: {new Date().toLocaleDateString()}</p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-black dark:text-white">1. Information We Do Not Collect (Image Data)</h2>
        <p>
          CompressPro operates on a strict local-processing model. <strong>We do not upload, transmit, store, or view the images you process using our tool.</strong> All image compression occurs locally on your device within your web browser. Your sensitive files remain entirely under your control.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-black dark:text-white">2. Analytics and Tracking</h2>
        <p>
          We use Google Analytics to understand how visitors interact with our website. This service collects standard internet log information and visitor behavior information in an anonymous form. The information generated by the Google Analytics cookie about your use of the website is transmitted to Google. This information is used to evaluate visitors' use of the website and to compile statistical reports on website activity.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-black dark:text-white">3. Cookies</h2>
        <p>
          Our website uses "cookies" (small data files placed on your device) to help provide a better user experience. In general, cookies are used to retain user preferences and provide anonymized tracking data to third party applications like Google Analytics. You may prefer to disable cookies on this site and on others via your browser settings.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-black dark:text-white">4. Changes to This Privacy Policy</h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.
        </p>
      </div>
    </div>
  );
}